sonar.projectKey=gearbox_apex
sonar.organization=gearbox


# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=apex
sonar.projectVersion=${SONAR_PROJECT_VERSION:-1.0}

sonar.python.version=3.13

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=tests

# Exclude third-party and configs from analysis
sonar.exclusions=.github/**/*,docs/**/*

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8

# Code coverage setup
sonar.python.coverage.reportPaths=coverage-unit.xml,coverage-integration.xml

# Exclude rules that are not relevant to our codebase
sonar.issue.ignore.multicriteria=ignoreS7503

sonar.issue.ignore.multicriteria.ignoreS7503.ruleKey=python:S7503
sonar.issue.ignore.multicriteria.ignoreS7503.resourceKey=**/*.py
