"""Initial migration (Add storage tables for user content)

Revision ID: 001
Revises:
Create Date: 2026-01-19 14:06:54.978471

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("worker_id", sa.String(length=100), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("generation_type", sa.String(length=20), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("enhanced_prompt", sa.Text(), nullable=True),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("theme_detected", sa.String(length=100), nullable=True),
        sa.Column("theme_confidence", sa.Float(), nullable=False),
        sa.Column("is_nsfw", sa.Boolean(), nullable=False),
        sa.Column("is_minor_suspected", sa.Boolean(), nullable=False),
        sa.Column("comfyui_prompt_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_generation_jobs_generation_type"),
        "generation_jobs",
        ["generation_type"],
        unique=False,
    )
    op.create_index(op.f("ix_generation_jobs_status"), "generation_jobs", ["status"], unique=False)
    op.create_index(
        op.f("ix_generation_jobs_theme_detected"),
        "generation_jobs",
        ["theme_detected"],
        unique=False,
    )
    op.create_index(
        "ix_generation_jobs_user_created",
        "generation_jobs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_jobs_user_id"), "generation_jobs", ["user_id"], unique=False
    )
    op.create_index(
        "ix_generation_jobs_user_status", "generation_jobs", ["user_id", "status"], unique=False
    )
    op.create_table(
        "user_images",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index("ix_user_images_cleanup", "user_images", ["expires_at"], unique=False)
    op.create_index(op.f("ix_user_images_expires_at"), "user_images", ["expires_at"], unique=False)
    op.create_index(
        "ix_user_images_user_created", "user_images", ["user_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_user_images_user_id"), "user_images", ["user_id"], unique=False)
    op.create_table(
        "generation_outputs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("input_image_id", sa.UUID(), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=10), nullable=False),
        sa.Column("output_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["input_image_id"], ["user_images.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["job_id"], ["generation_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(
        "ix_generation_outputs_cleanup", "generation_outputs", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_generation_outputs_expires_at"), "generation_outputs", ["expires_at"], unique=False
    )
    op.create_index("ix_generation_outputs_job", "generation_outputs", ["job_id"], unique=False)
    op.create_index(
        "ix_generation_outputs_user_created",
        "generation_outputs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generation_outputs_user_id"), "generation_outputs", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generation_outputs_user_id"), table_name="generation_outputs")
    op.drop_index("ix_generation_outputs_user_created", table_name="generation_outputs")
    op.drop_index("ix_generation_outputs_job", table_name="generation_outputs")
    op.drop_index(op.f("ix_generation_outputs_expires_at"), table_name="generation_outputs")
    op.drop_index("ix_generation_outputs_cleanup", table_name="generation_outputs")
    op.drop_table("generation_outputs")
    op.drop_index(op.f("ix_user_images_user_id"), table_name="user_images")
    op.drop_index("ix_user_images_user_created", table_name="user_images")
    op.drop_index(op.f("ix_user_images_expires_at"), table_name="user_images")
    op.drop_index("ix_user_images_cleanup", table_name="user_images")
    op.drop_table("user_images")
    op.drop_index("ix_generation_jobs_user_status", table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_user_id"), table_name="generation_jobs")
    op.drop_index("ix_generation_jobs_user_created", table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_theme_detected"), table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_status"), table_name="generation_jobs")
    op.drop_index(op.f("ix_generation_jobs_generation_type"), table_name="generation_jobs")
    op.drop_table("generation_jobs")
    # ### end Alembic commands ###
