"""Add Providers

Revision ID: 003
Revises: 002
Create Date: 2026-02-08 21:26:22.025098

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: str | None = '002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('provider', sa.String(length=20), nullable=False))
    op.add_column('generation_jobs', sa.Column('model', sa.String(length=50), nullable=True))
    op.add_column('generation_jobs', sa.Column('external_request_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_generation_jobs_model'), 'generation_jobs', ['model'], unique=False)
    op.create_index(op.f('ix_generation_jobs_provider'), 'generation_jobs', ['provider'], unique=False)
    op.create_index('ix_generation_jobs_provider_status', 'generation_jobs', ['provider', 'status'], unique=False)
    op.drop_column('generation_jobs', 'comfyui_prompt_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generation_jobs', sa.Column('comfyui_prompt_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_index('ix_generation_jobs_provider_status', table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_provider'), table_name='generation_jobs')
    op.drop_index(op.f('ix_generation_jobs_model'), table_name='generation_jobs')
    op.drop_column('generation_jobs', 'external_request_id')
    op.drop_column('generation_jobs', 'model')
    op.drop_column('generation_jobs', 'provider')
    # ### end Alembic commands ###
