"""add gpu session readiness marker

Revision ID: 008
Revises: 007
Create Date: 2026-05-19 18:24:44.567706

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "008"
down_revision: str | None = "007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gpu_sessions",
        sa.Column(
            "readiness_marker_node_class",
            sa.String(length=128),
            nullable=True,
            comment=(
                "ComfyUI class name to require in /object_info during readiness probe. "
                "NULL = fall back to 200-OK with ERROR log."
            ),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gpu_sessions", "readiness_marker_node_class")
    # ### end Alembic commands ###
